name: Deploy to Cloudflare Workers

on:
  push:
    branches: [ uat ]  # auto-deploy to UAT
  workflow_dispatch:  # allows manual trigger for prod

jobs:
  deploy-uat:
    name: Deploy to UAT
    runs-on: ubuntu-latest
    environment: uat
    if: github.ref == 'refs/heads/uat'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'
        cache: 'npm'
        cache-dependency-path: package-lock.json
    
    - name: Install dependencies
      run: npm ci
    
    
    # Skipping tests to avoid API key requirements in CI
    # Tests should still be run locally before pushing
    # - name: Run tests
    #   run: npm test -- --coverage --watchAll=false
    
    - name: Deploy to UAT
      run: npm run deploy:uat
      env:
    # must reference the secrets in the github actions secrets. create repo secrets in github and put dummy values.
        CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

        STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
        STRIPE_WEBHOOK_SECRET: ${{ secrets.STRIPE_WEBHOOK_SECRET }}
        SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
        OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
    # put the public variable values here.
        NEXT_PUBLIC_SUPABASE_URL: "https://yxgeebutldipbsqksotd.supabase.co"
        NEXT_PUBLIC_SUPABASE_PUBLISHABLE_OR_ANON_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl4Z2VlYnV0bGRpcGJzcWtzb3RkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5MjI3MjAsImV4cCI6MjA3MDQ5ODcyMH0.wJfbBxi7mRzQmrOS0h9YOoU_9nKzw2h-UcytbQEgv3c"
        NEXT_PUBLIC_SITE_URL: "write.uat.slowstack.cc"
        NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: "pk_test_51SHFo2Jn2qf03jwiSiRHerYus4RwHKd0uLeHNyHMR3D9rJ393B9tSyrDaCuk1Jowkrx1JrMD3OxfvpWBTRLjZACv007Zz3dGDY"
        TRIAL_PERIOD_SECONDS: "120"

  deploy-prod:
    name: Deploy to Production
    runs-on: ubuntu-latest
    environment: production
    if: github.event_name == 'workflow_dispatch'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'
        cache: 'npm'
        cache-dependency-path: package-lock.json
    
    - name: Install dependencies
      run: npm ci
    
    # Skipping tests to avoid API key requirements in CI
    # Tests should still be run locally before pushing
    # - name: Run tests
    #   run: npm test -- --coverage --watchAll=false
    
    - name: Deploy to Production
      run: npm run deploy:prod
      env:

        CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

      # must reference the secrets in the github actions secrets. create repo secrets in github and put dummy values.
        STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
        STRIPE_WEBHOOK_SECRET: ${{ secrets.STRIPE_WEBHOOK_SECRET }}
        SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
        OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
      # put the public variable values here. 
        NEXT_PUBLIC_SUPABASE_URL: "https://yxgeebutldipbsqksotd.supabase.co"
        NEXT_PUBLIC_SUPABASE_PUBLISHABLE_OR_ANON_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl4Z2VlYnV0bGRpcGJzcWtzb3RkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5MjI3MjAsImV4cCI6MjA3MDQ5ODcyMH0.wJfbBxi7mRzQmrOS0h9YOoU_9nKzw2h-UcytbQEgv3c"
        NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: "pk_live_51SHFnqJRJlz9rLh1cexv2Jf8rK8sp6Upc93StUvWRBer27EtpUKSfT6093Dw46S9kMIG5yB1wZhEmt4su6ogt08N002BW8a8Cs"
        NEXT_PUBLIC_SITE_URL: "write.slowstack.cc"
        TRIAL_PERIOD_SECONDS: "7776000"