name: Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: my-app/package-lock.json
    
    - name: Install dependencies
      working-directory: my-app
      run: npm ci
    
    - name: Run type check
      working-directory: my-app
      run: npm run type-check
    
    - name: Run linter
      working-directory: my-app
      run: npm run lint
    
    - name: Run unit tests
      working-directory: my-app
      run: npm test -- --coverage --watchAll=false
    
    - name: Upload coverage reports
      uses: codecov/codecov-action@v3
      with:
        directory: my-app/coverage
        fail_ci_if_error: true

  e2e-tests:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'
        cache: 'npm'
        cache-dependency-path: my-app/package-lock.json
    
    - name: Install dependencies
      working-directory: my-app
      run: npm ci
    
    - name: Install Playwright browsers
      working-directory: my-app
      run: npx playwright install --with-deps
    
    - name: Build application
      working-directory: my-app
      run: npm run build
    
    - name: Run E2E tests
      working-directory: my-app
      run: npm run test:e2e
      env:
        # Add any environment variables needed for E2E tests
        PLAYWRIGHT_TEST_BASE_URL: http://localhost:3000
        TEST_EMAIL: test@example.com
        TEST_PASSWORD: testpassword123
    
    - name: Upload Playwright report
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: my-app/playwright-report/
        retention-days: 30
